### ISSUE TITLE
Run with utplsql

### ISSUE THREAD

**Issue by LydiaAzzoug** [utPLSQL/utPLSQL#1207]
**Describe the bug**
It's not a bug but when i tested the function "TEST_ADDITION", it didn't mention that the two numbers that i compared are not equals  

**Provide version info**

I installed everything following the documentation
```sql
set serveroutput on
declare
  l_version varchar2(255);
  l_compatibility varchar2(255);
begin
  dbms_utility.db_version( l_version, l_compatibility );
  dbms_output.put_line( l_version );
  dbms_output.put_line( l_compatibility );
end;
/
select substr(ut.version(),1,60) as ut_version from dual;
select * from v$version;
select * from nls_session_parameters;
select substr(dbms_utility.port_string,1,60) as port_string from dual;
```

**Information about client software**
Client used to run utPLSQL: SQLDeveloper, 

**To Reproduce**

**Expected behavior**

**Example code**
Function TEST_ADDITION :
create or replace PACKAGE BODY PACKAGE1 AS

  FUNCTION TEST_ADDITION 
    (
  PARAM1 IN VARCHAR2  ,PARAM2 IN VARCHAR2 
) RETURN NUMBER AS
  BEGIN
    -- TODO : implémentation requise pour FUNCTION PACKAGE1.TEST_ADDITION
    RETURN PARAM1+PARAM2;
  END TEST_ADDITION;

END PACKAGE1;
 **Test**
create or replace package t3_package1 is

   --%suite
   --%suitepath(alltests)

   --%test
   procedure TEST_ADDITION;

end t3_package1;
/

create or replace package body t3_PACKAGE1 is

   --
   -- test
   --
   procedure TEST_ADDITION is
      l_actual   NUMBER;
      l_expected NUMBER := 4;
   begin
      -- arrange
   
      -- act
      l_actual:=TEST_ADDITION(1,2);
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   end TEST_ADDITION;

end t3_package1;
/

<img width="598" alt="Test" src="https://user-images.githubusercontent.com/98126863/165950078-f9a455bb-98a0-4503-a692-ecd7a7fc7ae4.PNG">

**Additional context**

**Comment by mathewbutler** [comment]
Hi - it doesn’t appear from the screen shot that any test were run. 

I can’t see that the test have been annotated as tests (—%test). This annotation is more than a comment, it marks the procedure as a test to be executed. Without this the procedure is ignored by utPLSQL (not considered as a test to be executed)

Here’s an example - search for “ Define specification for the test” which shows the use of the annotation. 
https://www.utplsql.org/utPLSQL/latest/userguide/getting-started.html

if you still have problems then I suggest following along with an example from the doco at the above link.  Once working you can experiment from there. 

Hope this helps. 
Mat.

**Comment by jgebal** [comment]
@LydiaAzzoug 
Please provide feedback so we can help you further or close the issue if the problem you were facing is now resolved.

**Comment by LydiaAzzoug** [comment]
Hello everyone,
I'am really sorry for this delay, I have a problem with my laptop, I can't
check utplsql now, by tomorrow I will get it back and I will let you know
if it works.

Sorry once again

Le sam. 30 avr. 2022 à 23:37, Jacek Gębal ***@***.***> a
écrit :

**Comment by LydiaAzzoug** [comment]
> @LydiaAzzoug Please provide feedback so we can help you further or close the issue if the problem you were f

**Comment by LydiaAzzoug** [comment]
Hi @everyone, 
I tried but it still doesn't work, the package t3_PACKAGE1 doesn't work also

**Comment by jgebal** [comment]
Hi @LydiaAzzoug 
Please let me know what happens if you execute the following script from SQLDeveloper as a script (using F5)

```sql
set serveroutput on
begin
  ut.run('t3_package1');
end;
```

**Comment by jgebal** [comment]
I have analysed your code and I've found some issues in code you have provided.
The lines:
```sql
  -- act
  l_actual:=TEST_ADDITION(1,2);
```
are wrong, and should be:
```sql
  -- act
  l_actual := package1.TEST_ADDITION(1,2);
```

So the example you have provided cannot work.

**Comment by jgebal** [comment]
Here is the code that worked for me on my local DB:
```
create or replace package package1 as
  function test_addition(
    param1 in varchar2, param2 in varchar2
  ) return number;
end package1;


create or replace package body package1 as
  function test_addition(
    param1 in varchar2, param2 in varchar2
  ) return number as
  begin
    -- TODO : implémentation requise pour FUNCTION PACKAGE1.TEST_ADDITION
    return param1 + param2;
  end test_addition;
end package1;

--Test
create or replace package t3_package1 is
  --%suite
  --%suitepath(alltests)

  --%test
  procedure test_addition;

end t3_package1;
/

create or replace package body t3_package1 is

  procedure test_addition is
    l_actual   number;
    l_expected number := 4;
  begin
    -- arrange

    -- act
    l_actual := package1.test_addition( 1, 2 );
    -- assert
    ut.expect( l_actual ).to_equal( l_expected );
  end test_addition;

end t3_package1;
/
```
See the animation below for results
![Test execution](https://user-images.githubusercontent.com/1398171/166241781-8cea019a-1251-4470-8e91-86c139a83884.gif)

**Comment by LydiaAzzoug** [comment]
Hi @everyone, thank you verry much for your help,  everything works perfectly
