### ISSUE TITLE
Wrong results on is_suite/has_suite/is_test when DDL trigger is disabled

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#979]
As reported by @PhilippSalvisberg , there is a problem with some of behaviors when DDL trigger is disabled.

To reproduce (run as UT3)
```sql
create or replace procedure do_check is
  t timestamp(6) := current_timestamp;
begin
  if ut_runner.has_suites(user) then
     dbms_output.put_line('true');
  else 
     dbms_output.put_line('false');
  end if;
  if ut_runner.is_suite(user, 'test_pkg') then
     dbms_output.put_line('true');
  else 
     dbms_output.put_line('false');
  end if;
  if ut_runner.is_test(user, 'test_pkg', 't1') then
     dbms_output.put_line('true');
  else 
     dbms_output.put_line('false');
  end if;
  dbms_output.put_line('Took: '||(current_timestamp-t));
end;
/

set serverout on
clear screen

alter trigger UT_TRIGGER_ANNOTATION_PARSING enable;

alter trigger UT_TRIGGER_ANNOTATION_PARSING disable;

create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

PROMPT should show false false false
exec do_check;
exec dbms_session.sleep(1);

create or replace package test_pkg is
  --%suite
  
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

PROMPT should show true true true
exec do_check;


drop package test_pkg;

PROMPT should show false false false
exec do_check;

alter trigger UT_TRIGGER_ANNOTATION_PARSING enable;

create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

PROMPT should show false false false
exec do_check;

create or replace package test_pkg is
  --%suite
  
  --%test
  procedure t1;

  --%Test
  procedure t2;

  procedure t3;
end test_pkg;
/

PROMPT should show true true true
exec do_check;


drop package test_pkg;

PROMPT should show false false false
exec do_check;



drop procedure do_check;
```

```

Trigger UT_TRIGGER_ANNOTATION_PARSING altered.


Trigger UT_TRIGGER_ANNOTATION_PARSING altered.


Package TEST_PKG compiled

should show false false false
false
false
false
Took: +000000000 00:00:00.006914000


PL/SQL procedure successfully completed.


PL/SQL procedure successfully completed.


Package TEST_PKG compiled

should show true true true
false
false
false
Took: +000000000 00:00:00.008096000


PL/SQL procedure successfully completed.


Package TEST_PKG dropped.

should show false false false
false
false
false
Took: +000000000 00:00:00.006847000


PL/SQL procedure successfully completed.


Trigger UT_TRIGGER_ANNOTATION_PARSING altered.


Package TEST_PKG compiled

should show false false false
false
false
false
Took: +000000000 00:00:00.021913000


PL/SQL procedure successfully completed.


Package TEST_PKG compiled

should show true true true
true
true
true
Took: +000000000 00:00:00.037328000


PL/SQL procedure successfully completed.


Package TEST_PKG dropped.

should show false false false
false
false
false
Took: +000000000 00:00:00.011410000


PL/SQL procedure successfully completed.


Procedure DO_CHECK dropped.

```

**Comment by PhilippSalvisberg** [comment]
it works for the first run in a fresh session
it fails for the subsequent runs in the same session (as shown above)

**Comment by jgebal** [comment]
OK there are two problems.
One fixed, another - debatable if it should be fixed.
1. I've switched from `systimestamp` to `current_timestamp` for no clear reason and it was causing package annotations not to be refreshed after object was changed (f your local time-zone is different than the DB time-zone).
Oracle registers `last_ddl_time` with DB time-zone

2. If in a single session you compile package with trigger `enabled` and run some of the frameworks functionalities like `is_suite` `ut.run` `get_suites` etc. framework will check if trigger is enabled once per session. If trigger gets disabled, you need to reconnect or invalidate session state for the framework to detect that trigger is now `off`.

Number 2 is an optimization to minimize the amount of checks done on each framework invocation.

I do not expect any regular DB to keep on switching the trigger state.

If trigger gets disabled or dropped, the framework will pickup all the DDL changes in invoked schema since the trigger was last operational.

Even though the trigger check isn't much of an overhead, I wouldn't enforce running the check on each framework invocation.

**Comment by PhilippSalvisberg** [comment]
Interesting. I do not understand the timezone issue, since `systimestamp` and `current_timestamp` deliver the same timezone on my system:

```
SQL> select systimestamp, current_timestamp from dual;

SYSTIMESTAMP
---------------------------------------------------------------------------
CURRENT_TIMESTAMP
---------------------------------------------------------------------------
21-JUL-19 08.27.40.784271 AM +02:00
21-JUL-19 08.27.40.784284 AM +02:00
```

Regarding is-trigger-enabled-caching. There I fully agree. No need to change that.

**Comment by pesse** [comment]
https://cleandatabase.wordpress.com/2018/12/18/100codeexamples-sysdate-vs-current_date/

**Comment by PhilippSalvisberg** [comment]
The question is, what is exactly the problem with `systimestamp` and `current_timestamp` when the db time zone and the session time zone are the same? - That's the situation I have. I understand the general issues when the time zone differs. But in my case they are the same and I still have issues with cache updates. So why should swapping `current_timestamp` with `systimestamp` should solve to issue in my case?

**Comment by pesse** [comment]
Sorry @PhilippSalvisberg ,I clearly missed the context. Shouldn't answer on a sunday morning from smartphone 🙈

**Comment by PhilippSalvisberg** [comment]
@pesse No worries.

**Comment by jgebal** [comment]
So I did a bit more digging.

Seems that the test-case I've provided doesn't work well due to the fact of disabling/enabling trigger after the framework was invoked in the same session.

And so I did another round of checks.
While performing my checks, everything is working as expected (using current develop version).
**v3.1.8.3169-develop**

And so I can't really figure out where is the problem
```sql
set serverout on
clear screen
set feedback on
set echo off

conn sys/... as sysdba
alter trigger ut3_latest_release.UT_TRIGGER_ANNOTATION_PARSING disable;
grant execute on ut3_latest_release.ut_trigger_check to ut3$user#;

conn ut3$user#/ut3

create or replace procedure do_check(a_expected boolean) is
  t timestamp(6) := current_timestamp;
begin
  ut.expect(
    ut_runner.has_suites(user), 'ut_runner.has_suites(user)'
  ).to_equal(a_expected);
  ut.expect(
    ut_runner.is_suite(user, 'test_pkg'), 
    q'[ut_runner.is_suite(user, 'test_pkg')]'
  ).to_equal(a_expected);
  ut.expect(
    ut_runner.is_test(user, 'test_pkg', 't1'),
    q'[ut_runner.is_test(user, 'test_pkg', 't1')]'
  ).to_equal(a_expected);
  dbms_output.put_line('Took: '||(current_timestamp-t));
end;
/

select substr(user,1,30) as "USER", substr(ut.version(),1,30) as version from dual;
set echo on
exec ut.expect(ut3_latest_release.ut_trigger_check.is_alive()).to_be_false;


create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(false);

create or replace package test_pkg is
  --%suite
  
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(true);

create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(false);

create or replace package test_pkg is
  --%suite
  
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(true);


exec ut_runner.purge_cache(user);

exec do_check(true);


create or replace package test_pkg is
  --%suite
  
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(true);


create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(false);

create or replace package test_pkg is
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(false);

create or replace package test_pkg is
  --%suite
  
  -- %test
  procedure t1;

  -- %Test
  procedure t2;

  procedure t3;
end test_pkg;
/

exec do_check(true);

drop procedure do_check;
```

```
SQL> clear screen
SQL> set feedback on
SQL> set echo off
Connected.

Trigger UT3_LATEST_RELEASE.UT_TRIGGER_ANNOTATION_PARSING altered.


Grant succeeded.

Connected.

Procedure DO_CHECK compiled


USER                           VERSION                       
------------------------------ ------------------------------
UT3$USER#                      v3.1.8.3169-develop           

1 row selected. 

SQL> exec ut.expect(ut3_latest_release.ut_trigger_check.is_alive()).to_be_false;
SUCCESS
  Actual: FALSE (boolean) was expected to be false


PL/SQL procedure successfully completed.

SQL> 
SQL> 
SQL> create or replace package test_pkg is
  2    -- %test
  3    procedure t1;
  4  
  5    -- %Test
  6    procedure t2;
  7  
  8    procedure t3;
  9  end test_pkg;
 10  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(false);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
Took: +000000000 00:00:00.060338000


PL/SQL procedure successfully completed.

SQL> 
SQL> create or replace package test_pkg is
  2    --%suite
  3    
  4    -- %test
  5    procedure t1;
  6  
  7    -- %Test
  8    procedure t2;
  9  
 10    procedure t3;
 11  end test_pkg;
 12  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(true);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
Took: +000000000 00:00:00.061089000


PL/SQL procedure successfully completed.

SQL> 
SQL> create or replace package test_pkg is
  2    -- %test
  3    procedure t1;
  4  
  5    -- %Test
  6    procedure t2;
  7  
  8    procedure t3;
  9  end test_pkg;
 10  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(false);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
Took: +000000000 00:00:00.055099000


PL/SQL procedure successfully completed.

SQL> 
SQL> create or replace package test_pkg is
  2    --%suite
  3    
  4    -- %test
  5    procedure t1;
  6  
  7    -- %Test
  8    procedure t2;
  9  
 10    procedure t3;
 11  end test_pkg;
 12  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(true);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
Took: +000000000 00:00:00.062777000


PL/SQL procedure successfully completed.

SQL> 
SQL> 
SQL> exec ut_runner.purge_cache(user);

PL/SQL procedure successfully completed.

SQL> 
SQL> exec do_check(true);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
Took: +000000000 00:00:00.060416000


PL/SQL procedure successfully completed.

SQL> 
SQL> 
SQL> create or replace package test_pkg is
  2    --%suite
  3    
  4    -- %test
  5    procedure t1;
  6  
  7    -- %Test
  8    procedure t2;
  9  
 10    procedure t3;
 11  end test_pkg;
 12  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(true);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
Took: +000000000 00:00:00.061801000


PL/SQL procedure successfully completed.

SQL> 
SQL> 
SQL> create or replace package test_pkg is
  2    -- %test
  3    procedure t1;
  4  
  5    -- %Test
  6    procedure t2;
  7  
  8    procedure t3;
  9  end test_pkg;
 10  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(false);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
Took: +000000000 00:00:00.055396000


PL/SQL procedure successfully completed.

SQL> 
SQL> create or replace package test_pkg is
  2    -- %test
  3    procedure t1;
  4  
  5    -- %Test
  6    procedure t2;
  7  
  8    procedure t3;
  9  end test_pkg;
 10  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(false);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: FALSE (boolean) was expected to equal: FALSE (boolean)
Took: +000000000 00:00:00.050566000


PL/SQL procedure successfully completed.

SQL> 
SQL> create or replace package test_pkg is
  2    --%suite
  3    
  4    -- %test
  5    procedure t1;
  6  
  7    -- %Test
  8    procedure t2;
  9  
 10    procedure t3;
 11  end test_pkg;
 12  /

Package TEST_PKG compiled

SQL> 
SQL> exec do_check(true);
SUCCESS
  "ut_runner.has_suites(user)"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_suite(user, 'test_pkg')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
SUCCESS
  "ut_runner.is_test(user, 'test_pkg', 't1')"
  Actual: TRUE (boolean) was expected to equal: TRUE (boolean)
Took: +000000000 00:00:00.073017000


PL/SQL procedure successfully completed.

SQL> 
SQL> drop procedure do_check;

Procedure DO_CHECK dropped.

Connection created by CONNECT script command disconnected
```


To be hones I'm running out of ideas.

@PhilippSalvisberg - can you provide exact steps to reproduce or is it the case related to disabling trigger in same session after running some tests?

**Comment by jgebal** [comment]
Note on previous comment:
>1. I've switched from systimestamp to current_timestamp for no clear reason and it was causing package annotations not to be refreshed after object was changed (f your local time-zone is different than the DB time-zone). Oracle registers last_ddl_time with DB time-zone

This was only done in my local and not pushed to develop hence it doesn't really apply.
Sorry for confusion.

**Comment by PhilippSalvisberg** [comment]
@gabal, I believe that you opened this issue based on utPLSQL/utPLSQL-SQLDeveloper#76. I wanted to use `has_suites` in earlier versions of utPLSQL but my JUnit tests failed and they are working for now the most recent utPLSQL version (3.1.8-develop). So, your observation that it is working in 3.1.8 is right. Nonetheless I would avoid using `current_timestamp` to ensure it's working also when DB and session time zone differ. With that change this issue can be closed IMHO.

However, to address the confusion created through all discussions I'd like to post here the excerpt of the JUnit tests (converted to plain PL/SQL) which shows that it is working in v3.1.8-develop but not in v3.1.7.

Steps to reproduce:

step 1:  deinstall utPLSQL

step 2: install utPLSQL v3.1.7, I used `install_headless.sql ut3 ut3`

step 3: run the following in a user without tests (I used `scott`):

```
set serveroutput on size unlimited
declare
  l_user varchar2(30) := lower(user); -- used 'scott' in original test
  procedure exec_sql(a_sql in varchar2) is 
  begin
    execute immediate a_sql;
  exception
    when others then
      null; -- ignore errors
  end exec_sql;
  function has_suites(a_owner in varchar2) return boolean is
    l_found integer;
  begin
    select count(*)
      into l_found
	  from table(ut_runner.get_suites_info(upper(a_owner)))
	  where item_type in ('UT_TEST', 'UT_SUITE');
    return l_found > 0;
  end has_suites;
begin
  --
  -- test 1
  --
  exec_sql('DROP PACKAGE junit_utplsql_test_pkg');
  exec_sql('CREATE OR REPLACE PACKAGE junit_utplsql_test_pkg IS
   -- %suite

   -- %test
   PROCEDURE t1;

   -- %Test
   PROCEDURE t2;

   PROCEDURE t3;
end junit_utplsql_test_pkg;');
  if ut_runner.has_suites(l_user) then
    dbms_output.put_line('test 1a - Looks good');
  else
    dbms_output.put_line('test 1a - Looks bad, suite not found.');
  end if;
  if has_suites(l_user) then
    dbms_output.put_line('test 1b - Looks good');
  else
    dbms_output.put_line('test 1b - Looks bad, suite not found.');
  end if;
  --
  -- test 2
  --
  exec_sql('CREATE OR REPLACE PACKAGE junit_utplsql_test_pkg IS

   -- %test
   PROCEDURE t1;

   -- %Test
   PROCEDURE t2;

   PROCEDURE t3;
end junit_utplsql_test_pkg;');
  if ut_runner.has_suites(l_user) then
    dbms_output.put_line('test 2a - Looks bad, suite should not be found.');
  else
    dbms_output.put_line('test 2a - Looks good.');
  end if;
  if has_suites(l_user) then
    dbms_output.put_line('test 2b - Looks bad, suite should not be found.');
  else
    dbms_output.put_line('test 2b - Looks good.');
  end if;
  --
  -- teardown
  --
  exec_sql('DROP PACKAGE junit_utplsql_test_pkg');
end;
/
```

I get the following output in my environment (19c version 19.4.0.0.0):

```
test 1a - Looks bad, suite not found.
test 1b - Looks good
test 2a - Looks bad, suite should not be found.
test 2b - Looks good.
```

step 4: deinstall utPLSQL

step 5: install development version of utPLSQL

step 6: rerun the code in step 3.

Then the result is:

```
test 1a - Looks good
test 1b - Looks good
test 2a - Looks good.
test 2b - Looks good.
```

So there was a change in 3.1.8 making `has_suites` more reliable. I'm 100% sure. Maybe it is related to the owner parameter which was case sensitive in v3.1.7 and in v3.1.8 not anymore. But that's just guessing.

**Comment by jgebal** [comment]
OK. So closing this issue, as not able o reproduce on 3.1.8 develop

**Comment by PhilippSalvisberg** [comment]
Yes, it’s fixed in v3.1.7.
